### ISSUE TITLE
Multiple Environments / Environment Switching

### ISSUE THREAD

**Issue by lukepighetti** [launchdarkly/flutter-client-sdk#11]
**Is your feature request related to a problem? Please describe.**
Best I can tell, the only way to switch environments right now is to call `LaunchDarkly.close()`, wait a few seconds, and then `LaunchDarkly.start()`. This works, but it would be nice to be able to switch environments without a race condition.

**Describe the solution you'd like**
A dedicated environment switching method like `LaunchDarkly.setActiveMobileKey(String mobileKey)`, or a way to have multiple LaunchDarkly clients, or a way to specify the mobile key for `allFlags()`

internal ref MOB-6143

**Comment by louis-launchdarkly** [comment]
Hello @lukepighetti, thank you for your interest in using the Flutter SDK. Multiple environments is a feature that was unfortunately not in the current 1.0 release but is on top of the Flutter roadmap. However, we don't have a target date for the multiple environment feature yet. I will mark this as an enhancement and will give you an update when the status changes.

Filed Internally as 93166.

**Comment by moribellamy** [comment]
This is also relevant for switching users. For example, a successful login requires a call to `LDClient.identify`. But flutter is allowed to call `build()` on my widget at any time, even after it is ejected from the widget tree.

There is no way I can guarantee the old screen (say, LoginScreen) will not have a callback that calls `LDClient.boolVariation` and gets an inappropriate value, since the "active user" is stored a a singleton outside of my reach.

**Comment by kinyoklion** [comment]
In the 4.0+ version of the SDK the client is no longer a singleton. This allows creating multiple clients with each one connected to a different environment.

Thank you,
Ryan
