### ISSUE TITLE
Null Safety Compatible

### ISSUE THREAD

**Issue by andrewescutia** [launchdarkly/flutter-client-sdk#3]
Hi,

Can we get an updated package that is Null Safety compatible? 

https://dart.dev/null-safety/migration-guide
https://dart.dev/null-safety

Thanks.

**Comment by bwoskow-ld** [comment]
Hi @andrewescutia,

We will keep this in mind for the upcoming 1.0 version of our Flutter SDK.

Right now this SDK is compatible with Flutter 1.x which means we're compatible with Dart versions which don't have null safety compatibility. Our understanding is that we'd have to drop support for Flutter 1.x in order to support features like this which were introduced in Flutter 2.0. This isn't to say that we won't do so -- but I wanted to explain some of our thinking on the topic.

We'll keep this issue open until the request is resolved.

Cheers,
@bwoskow-ld

**Comment by andrewescutia** [comment]
Ok I know that Flutter is making a big push for null safety and to get everything ported over. You'll also notice that even the Plugins that Flutter created and maintains themselves have been moved over: 
https://github.com/flutter/plugins#plugins

**Comment by cc-rock** [comment]
Null safety is now enabled by default for new Flutter project and the vast majority of dart packages already support it.. so in my humble opinion this should be a priority. Maybe what's not clear is that until you migrate, no Flutter project that uses null safety will be able to use Launch Darkly: this is much worse that having to drop Flutter 1.x, which is already quite obsolete.. unfortunately I couldn't find any statistics on how many Flutter apps have migrated already, but considering the tendency of Flutter devs to stay as up to date as possible, I'd say they are probably much more than those still based on Flutter 1.x.
Also.. Flutter 1.x users will still be able to use older versions, until they migrate.

**Comment by bwoskow-ld** [comment]
Hi all,

The LaunchDarkly SDK team has decided that the initial supported version (1.0.0) of this SDK will support Flutter 2.x -- not 1.x -- and _will_ support null safety. We don't have a concrete timeline to share in which this version will be available, but in the meantime we at least wanted to share with you our latest position.

In the meantime, this SDK remains available in a public beta and an unsupported state. We appreciate the feedback on it and welcome anything more you have to add to help shape upcoming releases.

Cheers,
@bwoskow-ld

**Comment by gwhelanLD** [comment]
I'm happy to announce that the [0.2.0 release](https://github.com/launchdarkly/flutter-client-sdk/releases/tag/0.2.0) of the SDK now supports null-safety. Thanks for your feedback on this beta SDK!

Thanks,
@gwhelanLD
